project:
  type: book

book:
  title: "Book of Imagery"
  reader-mode: true

  author: "Francisco Rowe, Ron Mahabir and Imago team"
  date: today

  page-footer:
    left: |
      Imago | UKRI Imagery Data Service
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  # cover-image: assets/Imago-logo.png
  favicon: assets/Imago-logo.png
  repo-url: https://github.com/Imago-SDRUK/book-of-imagery
  repo-branch: main
  repo-actions: [edit, issue]

  chapters:
    - index.qmd
    - chapters/intro.qmd
    - chapters/image-data.qmd
    - chapters/01_use-case-x.qmd
    - chapters/synthesis.qmd
    - chapters/way-forward.qmd
    - chapters/references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light:
        - style/theme.scss
      dark:
        - style/dark.scss
    include-in-header:
      text: |
        <script>
          document.addEventListener("DOMContentLoaded", function() {
            var sidebar = document.getElementById('quarto-sidebar');
            const anchor = document.createElement("a")
            anchor.setAttribute('href', 'https://imago.ac.uk')
            anchor.style.width = "100%"
            const image = document.createElement('img') 
            image.setAttribute('src', '/assets/Imago-logo.png')
            image.style.width = "100%"
            anchor?.appendChild(image)
            sidebar?.prepend(anchor)
          });
        </script>
  pdf:
    documentclass: scrreprt

editor: visual

